### ISSUE TITLE
icudt.dll

### ISSUE THREAD

**Issue by tazaar** [lonnc/golang-nw#13]
v0.10.0 of node-webkit changed icudt.dll to icudtl.dat

https://github.com/rogerwang/node-webkit/wiki/How-to-package-and-distribute-your-apps#which-files-should-be-shipped

A simple change in pkg/pkg.go fixed this.

**Comment by lonnc** [comment]
Fixed thanks to khaos-one in commit 29f4aaa054d09b04a0edcdf8e6bcd9b29b069b28
