### ISSUE TITLE
Copy-Paste isn't working on Mac

### ISSUE THREAD

**Issue by csaunders** [lonnc/golang-nw#17]
Looks like this can be fixed by improvements to the client `script.js` though I'm not super sure. Also I think there might be something broken on the later versions of nwjs.

Here's some of the related issues:

- https://github.com/nwjs/nw.js/issues/1955
- https://github.com/nwjs/nw.js/issues/2039

**Comment by tommoor** [comment]
Confirmed regressions in the 0.12 releases

**Comment by girishso** [comment]
Copy-paste does not work in Mac since the `Edit` menu is disabled by default. Resolved in PR https://github.com/lonnc/golang-nw/pull/19
